#!/usr/bin/env python3
"""Generate ``wiki/llms-wiki.txt`` — the whole architecture wiki in one file.

The wiki under ``wiki/`` is an Open Knowledge Format (OKF) 0.2 bundle: a directory
tree of Markdown pages carrying YAML frontmatter, which is right for humans and for
an agent that wants one subsystem. This script produces the other shape: every page
concatenated, in reading order, for dropping into a model's context whole.

Reading order is not configured here. It is derived from the bundle's ``index.md``
files, which OKF reserves for exactly that: the root index links the section
indexes, each section index links its pages, and this script walks that graph in
link order. A page no index links to is a page nobody can find, so ``--check``
fails on it.

Usage::

    python scripts/generate_wiki_llms.py            # write the bundle
    python scripts/generate_wiki_llms.py --check    # verify, write nothing

``--check`` exits non-zero when the bundle is stale, when a page is unreachable
from the indexes, when a page violates OKF conformance (unparseable frontmatter or
a missing ``type``), when a ``resource:`` names a file that no longer exists, or
when a relative link points at a file or heading anchor that does not exist
(renaming a heading in ``AGENTS.md`` is the most likely way this wiki rots). A page
past its ``stale_after`` date is reported as a warning, never a failure. Safe to
wire into CI or a pre-commit hook.

Note on OKF's permissiveness rule: the spec tells *consumers* to tolerate broken
links, because a broken link marks knowledge not yet written rather than an error.
That tolerance does not bind us as the bundle's authors, so the link check here
stays strict.

Deliberately NOT the same script as ``website/scripts/generate-llms-txt.py``: that
one covers ``website/docs`` (product documentation, published to the docs site) and
is regenerated by the Docusaurus prebuild. This one covers the architecture wiki
and is committed to the repo so a fresh clone has it without a build step.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
WIKI = REPO_ROOT / "wiki"
OUTPUT = WIKI / "llms-wiki.txt"

# Reserved by OKF: not concept documents, never carry a ``type``, never bundled.
RESERVED = {"index.md", "log.md"}

HEADER = """\
# Hermes Agent — Architecture Wiki (full)

Every page of wiki/ concatenated for LLM context ingestion, in reading order.
Generated by scripts/generate_wiki_llms.py — do not edit this file; edit the
pages under wiki/ and regenerate.

This wiki maps the codebase. The rules and rationale live in AGENTS.md, which
wins on any conflict. User-facing product documentation lives in website/docs/
and is bundled separately as website/static/llms-full.txt.
"""

# Matches [text](target).
_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
_HEADING_RE = re.compile(r"^#{1,6}\s+(.*)$", re.MULTILINE)
_FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
_FENCE_RE = re.compile(r"^```.*?^```", re.DOTALL | re.MULTILINE)
_INLINE_CODE_RE = re.compile(r"`[^`\n]*`")


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _slug(heading: str) -> str:
    """GitHub's heading-to-anchor rule, close enough for our own docs."""
    text = heading.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)  # drop punctuation, em dashes, backticks
    return re.sub(r"\s", "-", text)


def _prose(path: Path) -> str:
    """A page's text with fenced code blocks removed.

    A worked example of the index format inside a fence is documentation, not a
    link, and a ``#`` inside a shell fence is a comment, not a heading. Both must
    stay invisible to the link and anchor checks.
    """
    return _FENCE_RE.sub("", _read(path))


def _anchors(path: Path) -> set[str]:
    return {_slug(h) for h in _HEADING_RE.findall(_prose(path))}


def _pages() -> list[Path]:
    """Every concept document in the bundle: all .md except reserved and drafts.

    A leading underscore marks an authoring template (``_template.md``). It is a
    conformant OKF document but it documents nothing, so it stays out of both the
    bundle and the reachability check.
    """
    return sorted(
        p
        for p in WIKI.rglob("*.md")
        if p.name not in RESERVED and not p.name.startswith("_")
    )


def _frontmatter(path: Path) -> dict | None | str:
    """Parse a page's frontmatter. Returns the mapping, None if absent, or an
    error string if it is present but unparseable."""
    match = _FRONTMATTER_RE.match(_read(path))
    if not match:
        return None
    try:
        parsed = yaml.safe_load(match.group(1))
    except yaml.YAMLError as exc:
        return f"unparseable YAML frontmatter: {exc}"
    if parsed is None:
        return {}
    if not isinstance(parsed, dict):
        return "frontmatter is not a YAML mapping"
    return parsed


def _links(path: Path) -> list[str]:
    """Every real link on a page.

    Inline code spans are dropped first so a documented link *pattern* is not
    mistaken for a link. Dropping them cannot hide a real one: a link's backticks
    sit inside its text (``[`AGENTS.md`](../AGENTS.md)``), so the surrounding
    ``[...](...)`` survives intact.
    """
    return [t.strip() for t in _LINK_RE.findall(_INLINE_CODE_RE.sub("", _prose(path)))]


def reading_order() -> tuple[list[Path], list[str]]:
    """Walk the index graph from the bundle root, in link order.

    An index link to another ``index.md`` descends into that section; a link to a
    page appends it. First occurrence wins, so the task-routing shortcuts at the
    bottom of the root index cannot reorder or duplicate anything.
    """
    problems: list[str] = []
    ordered: list[Path] = []
    seen: set[Path] = set()
    walked: set[Path] = set()

    def walk(index: Path) -> None:
        # An index already walked is skipped rather than reported. Section indexes
        # link back up to the bundle root, and that back-link is navigation, not a
        # malformed bundle; page dedup below is what actually keeps order stable.
        if index in walked:
            return
        walked.add(index)
        for target in _links(index):
            if target.startswith(("http://", "https://", "mailto:", "#")):
                continue
            path_part, _, _ = target.partition("#")
            if not path_part:
                continue
            resolved = (index.parent / path_part).resolve()
            if not resolved.exists() or resolved.suffix.lower() != ".md":
                continue  # reported by check_links, not here
            if WIKI not in resolved.parents and resolved != WIKI:
                continue  # points outside the bundle (AGENTS.md, website/docs)
            if resolved.name == "index.md":
                walk(resolved)
            elif resolved.name.startswith("_"):
                continue  # an authoring template; an index may link it, the bundle skips it
            elif resolved not in seen and resolved.name not in RESERVED:
                seen.add(resolved)
                ordered.append(resolved)

    root = WIKI / "index.md"
    if not root.exists():
        problems.append("wiki/index.md is missing; the bundle has no root index")
        return [], problems
    walk(root)
    return ordered, problems


def check_coverage(ordered: list[Path]) -> list[str]:
    """Every page must be reachable from an index, and vice versa."""
    problems: list[str] = []
    reachable = set(ordered)
    for orphan in sorted(set(_pages()) - reachable):
        problems.append(
            f"{orphan.relative_to(WIKI)} exists but no index.md links to it"
        )
    for phantom in ordered:
        if not phantom.exists():
            problems.append(f"an index links {phantom.relative_to(WIKI)}, which does not exist")
    return problems


def check_okf() -> tuple[list[str], list[str]]:
    """OKF 0.2 conformance, plus the conventions this bundle adds on top.

    Conformance (spec §11): every non-reserved page parses as YAML frontmatter and
    carries a non-empty ``type``. Ours on top: ``resource`` must name a real path,
    and ``okf_version`` belongs to the root index alone (spec §12).
    """
    problems: list[str] = []
    warnings: list[str] = []
    today = date.today()

    for page in _pages():
        rel = page.relative_to(WIKI)
        data = _frontmatter(page)
        if data is None:
            problems.append(f"{rel}: no YAML frontmatter (OKF requires it)")
            continue
        if isinstance(data, str):
            problems.append(f"{rel}: {data}")
            continue
        if not str(data.get("type", "")).strip():
            problems.append(f"{rel}: frontmatter has no non-empty 'type'")
        if "okf_version" in data:
            problems.append(f"{rel}: okf_version belongs to the root index.md only")

        resource = data.get("resource")
        if resource and not str(resource).startswith(("http://", "https://", "git:")):
            if not (REPO_ROOT / str(resource)).exists():
                problems.append(f"{rel}: resource '{resource}' does not exist")

        stale_after = data.get("stale_after")
        if isinstance(stale_after, date) and stale_after < today:
            warnings.append(f"{rel}: past stale_after ({stale_after}); re-verify it")

    root = WIKI / "index.md"
    if root.exists():
        data = _frontmatter(root)
        if isinstance(data, dict) and "okf_version" not in data:
            warnings.append("index.md: no okf_version declared at the bundle root")
    return problems, warnings


def check_links() -> list[str]:
    """Relative links must resolve to a real file, and to a real heading anchor."""
    problems: list[str] = []
    anchor_cache: dict[Path, set[str]] = {}

    for page in sorted(WIKI.rglob("*.md")):
        for target in _links(page):
            if target.startswith(("http://", "https://", "mailto:")):
                continue

            path_part, _, fragment = target.partition("#")
            resolved = (page.parent / path_part).resolve() if path_part else page
            if not resolved.exists():
                problems.append(f"{page.relative_to(WIKI)}: broken link -> {target}")
                continue

            if not fragment or resolved.suffix.lower() != ".md":
                continue
            if resolved not in anchor_cache:
                anchor_cache[resolved] = _anchors(resolved)
            if fragment not in anchor_cache[resolved]:
                problems.append(f"{page.relative_to(WIKI)}: broken anchor -> {target}")
    return problems


def build_bundle(ordered: list[Path]) -> str:
    parts = [HEADER]
    for path in ordered:
        rel = path.relative_to(REPO_ROOT).as_posix()
        parts.append(f"\n\n---\n\n<!-- source: {rel} -->\n\n{_read(path).rstrip()}\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify conformance, coverage, links and freshness without writing",
    )
    args = parser.parse_args()

    ordered, problems = reading_order()
    okf_problems, warnings = check_okf()
    problems += check_coverage(ordered) + okf_problems + check_links()
    bundle = build_bundle(ordered)

    if args.check:
        current = _read(OUTPUT) if OUTPUT.exists() else ""
        if current != bundle:
            problems.append(
                f"{OUTPUT.relative_to(REPO_ROOT)} is stale — "
                "run: python scripts/generate_wiki_llms.py"
            )
        for warning in warnings:
            print(f"warning: {warning}", file=sys.stderr)
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"ok: {len(ordered)} pages, bundle up to date")
        return 0

    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)
    for problem in problems:
        print(f"warning: {problem}", file=sys.stderr)

    OUTPUT.write_text(bundle, encoding="utf-8")
    kib = len(bundle.encode("utf-8")) / 1024
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} — {len(ordered)} pages, {kib:.0f} KiB")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
