#!/usr/bin/env python3
"""Generate ``wiki/llms-wiki.txt`` — the whole architecture wiki in one file.

The wiki under ``wiki/`` is authored as one Markdown page per subsystem, which
is right for humans and for an agent that wants a single page. This script
produces the other shape: every page concatenated, in reading order, for
dropping into a model's context whole.

Usage::

    python scripts/generate_wiki_llms.py            # write the bundle
    python scripts/generate_wiki_llms.py --check    # verify, write nothing

``--check`` exits non-zero when the bundle is stale, when a page exists that
``PAGE_ORDER`` does not list, or when a relative link points at a file that does
not exist or at a heading anchor that no longer exists (renaming a heading in
``AGENTS.md`` is the most likely way this wiki rots). Safe to wire into CI or a
pre-commit hook.

Deliberately NOT the same script as ``website/scripts/generate-llms-txt.py``:
that one covers ``website/docs`` (product documentation, published to the docs
site) and is regenerated by the Docusaurus prebuild. This one covers the
architecture wiki and is committed to the repo so a fresh clone has it without
a build step.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WIKI = REPO_ROOT / "wiki"
OUTPUT = WIKI / "llms-wiki.txt"

# Reading order. Every ``wiki/*.md`` file must appear here; a new page that is
# not listed fails --check, which is the point — ordering is an editorial
# decision, not an alphabetical accident.
PAGE_ORDER: list[str] = [
    "index.md",
    "architecture.md",
    "agent-core.md",
    "tools.md",
    "terminal-backends.md",
    "cli.md",
    "gateway.md",
    "tui.md",
    "desktop.md",
    "dashboard-web.md",
    "state-and-sessions.md",
    "memory-and-context.md",
    "config-and-profiles.md",
    "providers-and-models.md",
    "plugins.md",
    "skills-and-curator.md",
    "mcp-and-acp.md",
    "scheduling.md",
    "testing-and-ci.md",
    "packaging-and-release.md",
    "glossary.md",
]

HEADER = """\
# Hermes Agent — Architecture Wiki (full)

Every page of wiki/ concatenated for LLM context ingestion, in reading order.
Generated by scripts/generate_wiki_llms.py — do not edit this file; edit the
pages under wiki/ and regenerate.

This wiki maps the codebase. The rules and rationale live in AGENTS.md, which
wins on any conflict. User-facing product documentation lives in website/docs/
and is bundled separately as website/static/llms-full.txt.
"""

# Matches [text](target) where target is a relative path (no scheme, no anchor-only).
_LINK_RE = re.compile(r"\[[^\]]*\]\(([^)]+)\)")
_HEADING_RE = re.compile(r"^#{1,6}\s+(.*)$", re.MULTILINE)


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _slug(heading: str) -> str:
    """GitHub's heading-to-anchor rule, close enough for our own docs."""
    text = heading.strip().lower()
    text = re.sub(r"[^\w\s-]", "", text)  # drop punctuation, em dashes, backticks
    return re.sub(r"\s", "-", text)


def _anchors(path: Path) -> set[str]:
    return {_slug(h) for h in _HEADING_RE.findall(_read(path))}


def _pages() -> list[Path]:
    return sorted(p for p in WIKI.glob("*.md"))


def check_coverage() -> list[str]:
    """Every wiki page must be listed in PAGE_ORDER, and vice versa."""
    problems: list[str] = []
    on_disk = {p.name for p in _pages()}
    listed = set(PAGE_ORDER)

    for missing in sorted(on_disk - listed):
        problems.append(f"{missing} exists but is not in PAGE_ORDER")
    for phantom in sorted(listed - on_disk):
        problems.append(f"PAGE_ORDER lists {phantom}, which does not exist")
    return problems


def check_links() -> list[str]:
    """Relative links must resolve to a real file, and to a real heading anchor."""
    problems: list[str] = []
    anchor_cache: dict[Path, set[str]] = {}

    for page in _pages():
        for target in _LINK_RE.findall(_read(page)):
            target = target.strip()
            if target.startswith(("http://", "https://", "mailto:")):
                continue

            path_part, _, fragment = target.partition("#")
            resolved = (page.parent / path_part).resolve() if path_part else page
            if not resolved.exists():
                problems.append(f"{page.name}: broken link -> {target}")
                continue

            if not fragment or resolved.suffix.lower() != ".md":
                continue
            if resolved not in anchor_cache:
                anchor_cache[resolved] = _anchors(resolved)
            if fragment not in anchor_cache[resolved]:
                problems.append(f"{page.name}: broken anchor -> {target}")
    return problems


def build_bundle() -> str:
    parts = [HEADER]
    for name in PAGE_ORDER:
        path = WIKI / name
        if not path.exists():
            continue
        parts.append(f"\n\n---\n\n<!-- source: wiki/{name} -->\n\n{_read(path).rstrip()}\n")
    return "".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify coverage, links and freshness without writing",
    )
    args = parser.parse_args()

    problems = check_coverage() + check_links()
    bundle = build_bundle()

    if args.check:
        current = _read(OUTPUT) if OUTPUT.exists() else ""
        if current != bundle:
            problems.append(
                f"{OUTPUT.relative_to(REPO_ROOT)} is stale — "
                "run: python scripts/generate_wiki_llms.py"
            )
        for problem in problems:
            print(f"error: {problem}", file=sys.stderr)
        if problems:
            return 1
        print(f"ok: {len(PAGE_ORDER)} pages, bundle up to date")
        return 0

    for problem in problems:
        print(f"warning: {problem}", file=sys.stderr)

    OUTPUT.write_text(bundle, encoding="utf-8")
    kib = len(bundle.encode("utf-8")) / 1024
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} — {len(PAGE_ORDER)} pages, {kib:.0f} KiB")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
